pipeline {
    agent {
        label 'helm3'
    }
    options {
  buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '3')
}
    stages {
        stage('Checkout Code') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/users/yogesh/self-hosted-runner']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Yogeshwaran-Palanisamy/gha-runners/']]
                    )
            }
        }
        stage('Install cert manager') {
            steps {
                container('helm') {
                script {
                    sh '''
                        curl -LO https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
                        helm template cert-manager oci://quay.io/jetstack/charts/cert-manager --version v1.19.2 --namespace cert-manager --create-namespace --verify --keyring ./cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg --set crds.enabled=true --output-dir .
                    '''
                }
                }
            }
        }
        stage('Render Helm Charts') {
            steps {
                container('helm') {
                script {
                    sh '''
                        helm template -f runners/gha-controller-value.yaml actions-controller oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller --namespace gha-controller --create-namespace --output-dir .
                    '''
                }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            when {
                branch 'main'
            }
            steps {
                script {
                    sh '''
                        kubectl apply -f rendered-manifest.yaml
                    '''
                }
            }
        }
    }
}